### ISSUE TITLE
Define formatting rules and reformat all sources according to them

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#10]
I have found that resources use different formatting (tab expansion / number of spaces per tab).

I think that we should use JBoss Community Formatting rules and try to stick to them:
https://community.jboss.org/wiki/ImportFormattingRules

**Comment by bleathem** [comment]
+1
I noticed webstrom is using different style rules for less and CSS.  Seems
to be confused with js.  Let's make sure that is nailed down in the jboss
rules.

**Comment by pauldijou** [comment]
Any chance to have support for Sublime Text 2? You know... a real text editor that doesn't get in your way when trying to code... #troll

**Comment by lfryc** [comment]
Hehe, let's say what you mean by supporting Sublime Text 2 then.
Whatever we can do can be attached to the wiki above. ;-)

**Comment by bleathem** [comment]
To be clear, we are agreeing on applying the non-java portion of the JBoss Formatting rules to all CSS, LESS, and JavaScript files in this project.  Those rules are:

> Line length is 128 characters
> Spaces are used instead of tabs
> Indentation size is 4

**Pros:** 
- Simple rules
- Common across JBoss projects

**Cons:**
- Both Bootstrap and lesscss.org use 2 spaces to indent their LESS files
  - OTOH: jquery uses [tabs for indentation](http://contribute.jquery.org/style-guide/js/) so we can't follow all upstream libraries

My vote is for the JBoss formatting rules, simply to have a well defined convention.

**Comment by pauldijou** [comment]
I think 4 spaces for LESS is too much. If you start using a bit of inheritance, it will quickly fly to the right of your IDE. In fact, I think 4 spaces is too much for any language with imbrications (meaning nearly all of them but not CSS !)

That's why tabs are nice. Each developer can set the width of a tab as he wants. I've always been using spaces, but lately, I've started to think tabs might be better... See http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/

Time for a small revolution inside JBoss? :-)

**Comment by bleathem** [comment]
In an external discussion we have agreed to use 2 spaces for all RichFaces widget sources.

**Comment by bleathem** [comment]
Re-opening as we have further issues to discuss/refine.
- mix of 
  - hyphenation in LESS/CSS (inherited from Bootstrap), eg. ordering-list
  - camelCase in javascript, eg. orderingList
  - #agreed: filenames use hyphen
- mix of single quotes ' and double quotes " for javascript strings
  - #agreed use single quotes
- Namespace of widgets
  - #agreed we will use `rich` as the widget namespace (not `rf` nor `ui`)
- _Prefix on names widgets_
  - potential collision with jQuery UI jQuery plugin names
  - eg. richAutocomplete vs. jQuery UI autocomplete
- widgetEventPrefix of widgets (widget factory)
  - #agreed no "_" in prefix, stick with default of widget name (stick with default)
- use of self/that/widget for closure references
  - #agreed use widget where it makes sense, use that otherwise
- initializing widget options to null vs. undefined
  - #agreed use null
- whitespace between property name and function (yes/no)
  - #agreed "no space"
- whitespace between function keyword and parens ()  (yes/no)
  - #agreed "no space"

**Comment by bleathem** [comment]
Some jshint rules that can help us achieve some consistency:
- camelcase:true
- quotmark:single
- indent:2

**Comment by lfryc** [comment]
Hey Brian, what of those mentioned ^ rules are missing atm.?

**Comment by bleathem** [comment]
We discussed outstanding issues, I will summarize them in CONTRIBUTING.adoc

**Comment by bleathem** [comment]
@lfryc can you review my changes to the contributing readme:
http://richwidgets.github.io/contributing.html

Then we can resolve this issue.  We can further refine further style issues moving forward either ad-hoc of by filing a new issue.

**Comment by lfryc** [comment]
I have updated coding-style conventions with samples of usage:
https://github.com/richwidgets/richwidgets/commit/54fdfecf8598544c34928780d984b9fab1b9d8a9

Generally looks fine.

I have few missing points there:
- we need to discuss widget prefixing (such as `richAutocomplete` vs `autocomplete`
  - in my opinion, if our widget depends on some third-party widget (or even overrides it), we should do a quick check: 
  - `if (!$.ui.autocomplete) { console.log.error('jQuery UI Autocomplete needs to be loaded to allow Autocomplete function properly'); }`
- I'm missing lifecycle methods ordering we have discussed (having single convention helps  contributors to become familiar with the code quickly)
  - my notes:
    1. lifecycle methods (e.g. `_create`, `_destroy`, `_enable`, `_disable`)
    2. public API methods (e.g. `showPopup()`)
    3. private methods
       1. initialization methods (e.g. `_initDom()`, `_bindListeners()`
       2. cleanup methods (E.g. `_cleanDom()`)
       3. event handlers
       4. other private methods

**Comment by lfryc** [comment]
Remaining issues:
- [x] rename pickList.js / orderingList.js to pick-list.js / ...
- [x] pickList / orderingList - widget namespace rf -> rich
- [x] pickList / orderingList - destroy -> _destroy (no need for prototype call then)
- [x] pickList / orderingList - order of methods as defined in conventions
- [x] autocomplete - order of methods
- [ ] chart review (once impl completed by @Lukindo )
