### ISSUE TITLE
Refactor usage of icon classes to comply with new font-awesome usage

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#131]
Brian suggested to use `rich-icon-` or `rw-icon-` prefixes on a team meeting.

https://community.jboss.org/wiki/RichFacesTeamMeetingAgenda2013-11-12#comment-13010

**Comment by bleathem** [comment]
As an example of where this would be applicable see:
https://github.com/richwidgets/richwidgets/blob/master/src/widgets/select/select-list.less#L240
https://github.com/richwidgets/richwidgets/blob/master/src/widgets/select/pick-list.less#L81

Here I defined a series of `icon-*` classes rather than embed the fontawesome class directly.  This allows one to _easily_ override which icon is used in the ordering list buttons.

The suggestion in this issue is to use a `rich*` prefix rather than the more generic `icon-*` prefix similar to the way Bootstrap uses `glyphicon` and font awesome uses `faicon`.  For a discussion on the relative merits of using such a prefix, see the discussion in this font-awesome issue: https://github.com/FortAwesome/Font-Awesome/issues/940

I suggest we use `richicon` to be consistent with the naming approach used in our upstream libraries.
