### ISSUE TITLE
Dev Review Chart widget

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#27]

**Comment by lfryc** [comment]
Review Examples, API and suggest improvements

**Comment by lfryc** [comment]
Examples review:
- years: 1990.0 - there is a unnecessary ".0"
- labels: some labels contain %s string

API notes:
- there are [twice data: { data: ... } }](https://github.com/richwidgets/richwidgets/blob/master/src/demos/pages/output/charts/category-bar-chart.js#L5)
- [class identifiers from Java](https://github.com/richwidgets/richwidgets/blob/master/src/demos/pages/output/charts/line-chart.js#L14) (e.g. `ytype:'class java.lang.Number'`)

Code-style:
- identation should be 2 spaces, but chart demos/sources use 4 spaces per tab

**Comment by lmacko** [comment]
Examples:
- it was caused by the width of chart. There is set max-width https://github.com/richwidgets/richwidgets/issues/58 ".0" should not appear.
- this issues is related to flot tooltip plugin https://github.com/richwidgets/richwidgets/issues/24

API notes:
- the nested data is used internally by flot, the outer data is there beacuse orginal flot use three options `$.plot(placeholder,options,data)` and jquery widget use only options so data is moved to option structure. 
- I plan to replace them by shorter ones number/string as soon as the new chartBridge is done

Code-style:
- fixed 5c15067d7233eb49b9101402c370039c34a45422

**Comment by bleathem** [comment]
@Lukindo what's the status of the chart widget API?  Is it yet ready for a review?

**Comment by lmacko** [comment]
Yes, it is ready for a review from my point of view.

**Comment by bleathem** [comment]
https://github.com/richwidgets/richwidgets/blob/master/src/widgets/output/chart.js

**Comment by bleathem** [comment]
1. Why are [`pieDefaults`](https://github.com/richwidgets/richwidgets/blob/master/src/widgets/output/chart.js#L165) and [`dateDefaults`](https://github.com/richwidgets/richwidgets/blob/master/src/widgets/output/chart.js#L177) separate from the `options` object?

Otherwise the code in chart.js looks good.  My only other comment would be addressing the Public API and the lack of _trigger events and corresponding handlers.  But we'll address that in a future issue for the 0.2 milestone.

**Comment by lmacko** [comment]
The `options` object includes options and their defaults values for all (types of) charts. The `pieDefaults` or `dateDefaults` should be applied only if pie chart or date chart is used. I am not sure if it is correct approach. If there is better way how deal with it, let me know.

**Comment by bleathem** [comment]
@Lukindo that's an interesting problem.  Let's leave it as is for now, and reconsider other solutions when we address the public API in the RichWidgets 0.2 release.
