### ISSUE TITLE
Generate examples to dist and rewrite their links to minified resources

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#3]
Currently, it's not clear whether the examples should reference /src resources or /dist resources.

I propose the examples will be copied to /dist folder, and all the resource links will be rewritten using `usemin` grunt task.

Discussed here: https://community.jboss.org/message/820033#820033

**Comment by pauldijou** [comment]
For me, `examples` will be a standalone website containing doc and samples. If the name isn't explict enough, I can rename it to "doc" or whatever. That said, I see no reason to copy it to the `dist` folder, both serve different purposes.

Tests shouldn't care about which files they are testing, it's a matter of configuration. So all tests should run on both source files (from `src`) and compiled files (from `dist`). I think it's just a matter of Karma configuration. The second test is more about testing we didn't broke anything during concatenation and minification.

In dev, doc and samples should run on source files in order to ease debugging. In production, we can definitely use these grunt plugin to merge them all but I wonder if it would be better for users looking at the source code of the website to have unminified files.

**Comment by bleathem** [comment]
This was resolved with commit: https://github.com/richwidgets/richwidgets/commit/b3a44b3c46177da95497a4c0a6bd98c2ca90f61e
