### ISSUE TITLE
Test "widget(pickList): source pickList from <table> markup" fails on Chrome

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#41]
The test pass on PhantomJS, but doesn't pass on Chrome:

https://gist.github.com/lfryc/00dc1ac13d038e767b20

**Comment by ppitonak** [comment]
assign it ot Jiri, please

**Comment by jstefek** [comment]
The 'fill-item' element seems to render differently on each browser. The height in its style for provided target table is different:
- PhantomJS 88px,
- FF 99px (also 'fill-item' in source table has 1px instead of 0px), 
- Chrome 98px,
- (Opera 99px.)

@lfryc what are the options for resolving this issue? Detecting browser in test and switching the expected html source? Do we already have such detector? Or are there any other options?

**Comment by lfryc** [comment]
In autocomplete, I have resolved the issue by importing bootstrap.css which resets the sizes of certain elements in order to unify them.

Additionally, I have put Autocomplete into <div> which normalizes its width.

After my changes, the tests were stable between Chrome, FF and PhantomJS.

If we won't be able to stabilize the test, we will need to come with unification strategy (dom-compare hook/extension).

**Comment by jstefek** [comment]
@lfryc 
the bootstrap.css is loaded. Where have you put the autocomplete in?

---

The only thing that 'works' (Chrome + PhantomJS, but not FF -- there is still problem with  _fill-item_  in source list) is setting the style (height) for _.target_ and _.source_ , however it completely breaks styling and computing of _fill-item_ (=the visual output is broken, also one dnd test will fail due to this, but it can be easily fixed). So it is definitely a bad idea.

I am not sure if I can fix it without a hack with setting the _height_ value of that _fill-item_. Would it be a problem if we can check that problematic _height_ in test with some tolerance and then set it to an expected value so the DOM comparator will pass?

**Comment by lfryc** [comment]
@jstefek we could introduce `ignoreStyleAttribute` configuration option for dom-compare and then verify this attribute manually.

**Comment by bleathem** [comment]
We could try putting the test fixtures in a fixed-height element, this may help the computed height of the fill elements to be consistently sized.
