### ISSUE TITLE
Dist structure

### ISSUE THREAD

**Issue by bleathem** [richwidgets/richwidgets#5]
Determine how we will structure the dist folder to meet as many use cases as we can foresee.

**Comment by pauldijou** [comment]
Let's generalize the question: how should we deliver the library? I think we need to cover a large range of possibilities from the really lazy user who only want to drop one CSS and one JS file to the hardcore user who want to use its custom Bootstrap LESS files.

The best way would probably be a website allowing users to customize their build. Something like http://twitter.github.io/bootstrap/customize.html. So you would be able to check/uncheck widgets but also dependencies if you want to embed them. Depending on the widgets selected, the website should tell you which dependencies are really required (for example, you don't need select2 if you don't want the autocomplete widget).

As for raw files, I wouldn't bother much. For JS:
- the concatenation of all our JS files (no third-party library in it)
- the minification of the previous one
- the concatenation and minification of all JS files, including source files and third-party libraries (the one to rule them all, fatty file)

As for CSS, we can't really publish a CSS file containing only our code since it will rely a lot on Bootstrap design (a huuuuuge lot). So:
- the compiled version (unminified CSS of Bootstrap + Fontawesome + our code)
- the compiled and minified version

**Comment by lfryc** [comment]
I agree that including third-party resources is totally convenient
- we should simplify a way how people consume a dependencies, we will do
  testing against particular versions, etc.
- people can upgrade if they want, but we should at least have
  `third-party` or `lib` folder with third-party dependencies the widget
  suite relies upon

**Comment by bleathem** [comment]
Proposal:

1) Provide compiled, yet distinct, assets in the `/dist/assets` folder
- /dist/assets/[3rd-party-lib]/resource.{js|css}
- /dist/assets/richfaces/richfaces.min.{js|css}
- /dist/assets/richfaces/[widget-family]/resource.{js|css}

where <3rd-party-lib> would be one of "jquery", "font-awesome", "bootstrap", "jquery-ui".

2) provide two top level "everything files" that package all the resources into discreet files:
- richfaces-widgets.{js|css}

3) Adjacent to this, we would have the compiled/standalone examples.  Examples in the dist folder  should reference the resources in either the assets folder, or the top-level minified resources:
- /dist/examples/_._

The above assets structure then has enough structure to enable RichFaces to map accordingly, without forcing JSF naming semantics on other use cases.

**Comment by lfryc** [comment]
Hey Brian,

ad 1) I like that, as you said the structure doesn't imply anything JSF, however we should take into consideration that we are using general naming here. e.g. `META-INF/resources/bootstrap` is a resource folder I would use to store my bootstrap resources. So we can expect collisions and problems which will arise from it.

The solution is namespacing everything in RF: `dist/assets` -> `META-INF/resources/org.richfaces/{bootstrap,font-awesome,jquery-ui,richfaces}`

ad 2) +1 - I like the uber-files richfaces-widgets.js/css, because it will be huge improvement for people starting with development: you just reference one file and start to code an app without worrying of managing dependencies. You can take care of building optimized resources later.

ad 3) +1

**Comment by lfryc** [comment]
Okay, we have agreed offline to:
- rename `dist/assets/org.richfaces` to `dist/assets/richfaces`.
- map following resources in Maven build:

```
/dist/assets/richfaces -> META-INF/resources/org.richfaces/widgets/ (Because of livereload)
/dist/assets/jquery/ -> META-INF/resources/com.jquery/
/dist/assets/jquery-ui/ -> META-INF/resources/com.jqueryui/
/dist/assets/bootstrap -> META-INF/resources/bootstrap/
/dist/assets/font-awesome -> META-INF/resources/font-awesome/
```

**Comment by pauldijou** [comment]
Hey there,

Globally agree with the solution. Some details:

1) Why having "richfaces-widgets.{js|css}" once at top level and "richfaces.{js|css}" inside the richfaces folder? Wouldn't it be better the other way? Inside the `richfaces` folder, it will only be the widgets, where the top level can be seen as the whole richfaces packaged.

2) I've never been a huge fan of generic names like `resources.{js|css}`. It's true that there will be no confusion since it's in separated folder, but when you open them in your editor ou IDE, it will be either a bunch of `resources.{js|css}` or all those `[widget]/resources.{js|css}` taking all your horizontal size really quick because of all those "useless" `resources`.

To be honnest, I'm not a huge fan of the following solution since it's quite WET, but still, I think I would prefer having `[widget]/widget.{js|css}`

3) I'm fine with this solution, because for classic users it will be easier to have all dependencies in the repo, but that's not the Bower spirit. If we wanted to go more nicely with Bower, we wouldn't put any 3rd party library in our assets since we can specify richfaces-widgets as being dependent on others libraries as jQuery or Lo-Dash or whatever. Then, installing rchfaces-widgets with Bower would automagically fetch all those dependencies.

**Comment by lfryc** [comment]
3) Let's remember that `dist/assets` is not Bower distribution. Nor it is JSF distribution. Question is what it actually is then. :-) Ideas?

E.g. Angular distributes Bower packages in completely [separated repos](https://github.com/angular/bower-angular).

2) Me either, even `jquery-ui` doesn't use families - they have just plain structure. I think this was designed to align widgets with JSF component's packages.

1) right, I missed that - `assets/richfaces.min.{js,css}` it should be

**Comment by pauldijou** [comment]
3) IMHO, totally humble, Angular is doing it soooooo wrong (for real, but just for that, otherwise, it's awesome). That's because they probably only want to serve compiled files, which is no good because more and more devs want to have the source code to dive on it if required, or build from source with some modifications. Hiding the reality never solve the problem.

Also, there are only tags from 1.0.3 to 1.0.7. So all good guys using 1.1.x are just... [insert not a nice word here]. In my current AngularJS project, to use it with Bower, I need to point direct to their real repo, clone the source, and then build from source. Thanks god, someone created Grunt.

Any new library in the JavaScript world should be ready to be Bower compatible since it's more and more used right now. The only idea of Bower is cloning a repo at a certain tag and then do the same to all dependencies.

For example, AngularUI requires Angular ([see bower.json](https://github.com/angular-ui/ui-utils/blob/master/bower.json)) but you will not find it in the AngularUI repo. Same for any jQuery plugin.

So I'm not fully sure of the benefit of having all those files on assets. I don't really care about them taking some disk space after cloning. I'm a bit concern when updating Bower dependencies because you will download them each time and twice (one inside RF widgets, and once because we will have dependencies to them of course).

Do we need them for JSF purpose or not? Just to be sure.

1) There will also be a non-minified file, right?

**Comment by lfryc** [comment]
1) it can be, do you find it necessary? I guess it will help debugging a lot.

3) That's right, I also faced missing Angular version issue, but that's just about poor management on team's side. (Btw they actually [distribute sources together with minified version.](https://github.com/angular/bower-angular/blob/master/angular.js))

I have problem with distributing assets together with sources: every time you change something, distribution changes as well - the history of commits is screwed then. Additionally, it may happen that people won't accidentally recompile / commit changes, so source code and distribution will start to differ. Feels like a bit fragile.

We could overcome it and distribute assets just in tagged releases, but it seems inconsistent.

Anyway, I think that I will need to overcome my own purity here and commit distribution assets together with rest of framework. As we already said, it makes JSF side of thinks easier (no need to execute anything in Maven build).

**Comment by lfryc** [comment]
Current structure:
https://github.com/richfaces/richfaces-widgets/tree/master/dist/assets

**Comment by lfryc** [comment]
Okay, I think that we have nailed the default structure down,

if you have any more comments we can either open new issues or reopen this one.

Agree?

**Comment by bleathem** [comment]
We seem to have settled on a workable dist.  Closing.
