### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by lfryc** [richwidgets/richwidgets#6]
based on...
- bootstrap-typeahead
- or typeahead.js
- or jQuery UI
- or select2

**Comment by lfryc** [comment]
I think we should leave out multi-complete feature, it is well suited for select2 and it's tag-completion, see
Auto Tokenization sample in http://ivaynberg.github.io/select2/

**Comment by pauldijou** [comment]
For what I know, the `typeahead.js` is probably the best in term of performance so far and allow great customization. The Bootstrap one is more a nice small widget rather than an optimized real-world component. I don't know much about the jQuery UI one, it has nice feature but I'm not a huge fan of jQuery UI except for some high level concepts like the factory.

So, for me, the main question is: should we use only one tool to rule them all (aka select2) or do we matter about such optimization and consider typeahead.js? Since select2 is really good, I'm not sure it worth it (also considering the increase of dependencies by one), but some collegues of mine have found that for simple autocomplete, typeahead.js looks better.

**Comment by lfryc** [comment]
I though initially we could use just select2, but it turns out, it doesn't have any mode which would enable simple autocompletion as we know it from RF - simple input box + suggestion box.

This is something which can certainly be done with customization though, reusing the suggestion box.
This approach would allow us to have unified l&f for suggestion boxes.
But certainly it stretches the muscles of select2 and its intended usage.
