### ISSUE TITLE
orderingList: item contains new style attribute after dragging

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#83]
- open http://www.richwidgets.io/select/orderingList.html
- drag and drop few items (e.g. 1st, 2nd)
- after drop all these previously dragged items contains new attribute _style='display: block;'_

If you destroy that changed orderingList, these styles will remain (and it will break the list styles)

**Comment by lfryc** [comment]
I think that we could rather leverage styling by classes that can be removed - that approach wouldn't polute DOM with style attribute changes.

**Comment by lfryc** [comment]
@jstefek have you identified any test where it makes issues?

**Comment by jstefek** [comment]
@lfryc no, there is no such test now

**Comment by bleathem** [comment]
This is a side-effect of the jQuery UI sortable plugin using the jQuery#show/hide methods to show and hide elements.

From the jQuery docs for the show method:

> This is roughly equivalent to calling .css( "display", "none" ), except that the value of the display property is saved in jQuery's data cache so that display can later be restored to its initial value.

This seems to be a commonly observed phenomenon:
- http://stackoverflow.com/questions/15689966/jquery-show-adds-style-displayinline-block-to-elements
- http://stackoverflow.com/questions/3989388/jquery-show-keeps-adding-displayblock

We could try upgrading jQuery to see if the problem is still observed.

**Comment by bleathem** [comment]
IMO we'll have to ignore this attribute.  It has no functional side-effect, and working around it may in fact intorduce such a functional side-effect.

To get the test to pass, and resolve this issue, we'll have to implement the ignore attribute functionality that @lfryc has brainstormed about elsewhere.
